elements: Fix selection of groups
And add a test where we were getting:

  AttributeError: 'NoneType' object has no attribute 'get_children'

because of that.